graphnav_builder:
  ros__parameters:
    odom_topic: odom
    grid_map_topic: traversability_map
    nav_graph_topic: nav_graph
    traversability_layer: ""
    trav_class: default
    safe_threshold: 0.5
    local_map_radius: 10.0
    local_map_resolution: 0.1
    max_free_radius: 4.0
    traversable_radius: 0.5
    edge_radius: 8.0
    num_samples: 1000
    random_seed: 7
