# Robot Parameters
num_cameras: 3
parent_frame: odom
cam_frame: wildos_{}_camera_color_optical_frame
lidar_frame: odom
object_mask_topic: /object_mask
lidar_topic: /dlio/odom_node/pointcloud/deskewed

# Publisher topics
triangulated_object_topic: /triangulated_object
navigation_goal_topic: /imgnav_waypoint
particle_viz_topic: /object_hypotheses
goal_direction_viz_topic: /goal_direction

# ROS2 subscriber params
qos_history_depth: 10
syncsub_queue_size: 10
syncsub_slop: 0.3

# Triangulation config
max_views: 350
min_lidar_points: 60
min_view_distance: 0.75
particle_generator_config:
  num_particles: 1000
  depth_range: [1.0, 80.0]
  add_odom_drift: false
use_mask_for_projection: true

# TFLookup Config
buffer_size: 10
timer_duration: 0.2
