# Model Params
frontier_ckpt: /root/ros2_ws/src/nebula2-wildos-main/ckpts/frontier_head.ckpt
traversability_ckpt: /root/ros2_ws/src/nebula2-wildos-main/ckpts/trav_head.ckpt
model_version: c-radio_v3-b
adaptor_version: null
use_naclip: true
use_summary_for_spatial: true
radio_dim: 768
static_scale_factor: 0.75
model_precision: FP32

# Camera-only ExploRFM probe.
num_cameras: 3
cams_inverted: false
fig_resize_factor: 0.45
camera_img_topic: /wildos/{}/color/image_raw

# Outputs.
model_viz_topic: /explorfm_probe/model_visualization
stats_topic: /explorfm_probe/stats
map_topic_prefix: /explorfm_probe/maps
publish_raw_maps: true

# Subscriber params.
qos_history_depth: 10
syncsub_queue_size: 30
syncsub_slop: 0.2
process_every_n: 1
